import argparse

def parse_args():
    parser = argparse.ArgumentParser(description='GCNA4MDA')
    parser.add_argument('--seed', type=int, default=1024)
    parser.add_argument('--root-path', type=str, default='./data')
    parser.add_argument('--device', type=str, default='cuda:0')
    parser.add_argument('--num_miRNA', type=int, default=1245)
    parser.add_argument('--num_disease', type=int, default=2077)
    parser.add_argument('--num_ent', type=int, default=1245 + 2077)
    parser.add_argument('--miRNA_simi_path', type=str,default='./data/miRNA_miRNA.npy')
    parser.add_argument('--disease_simi_path', type=str,default='./data/disease_disease.npy')
    parser.add_argument('--miRNA_disease_adj_path', type=str,default='./data/miRNA_disease.npy')
    parser.add_argument('--miRNA_rfam_path', type=str,default='./data/mirna_rfam.npy')
    parser.add_argument('--miRNA_cluster_path', type=str,default='./data/miRNA_cluster.npy')
    parser.add_argument('--miRNA_targets_path', type=str,default='./data/miRNA_targets.npy')
    parser.add_argument('--miRNA_targets_adj_path', type=str,default='./data/mirna_targets_ADJ.npy')
    parser.add_argument('--kfolds', type=int, default=5)
    parser.add_argument('--train_ratio', type=float, default=0.8)
    parser.add_argument('--test_ratio', type=float, default=0.2)
    parser.add_argument('--lr', type=float, default=0.0005)
    parser.add_argument('--weight', type=float, default=0.0)
    parser.add_argument('--epochs', type=int, default=200)
    parser.add_argument('--epoch_relgan', type=int, default=80)
    parser.add_argument('--in_dim', type=int, default=128)
    parser.add_argument('--hidden_dim', type=int, default=128)
    parser.add_argument('--num_views', type=int, default=3)
    parser.add_argument('--lambda_reg', type=float, default=1e-4)
    parser.add_argument('--threshold', type=float, default=0.9)
    # main.py
    parser.add_argument('--learn_rate', type=float, default=1e-4)
    parser.add_argument('--weight_decay', type=float, default=5e-3)
    parser.add_argument('--epoch', type=int, default=50)
    parser.add_argument('--kernel_size', type=int, default=7)
    parser.add_argument('--batch', type=int, default=10000)
    params = parser.parse_args([])
    return params

args = parse_args()
